### ISSUE TITLE
[Info] Guitarix now integrated RTNeural

### ISSUE THREAD

**Issue by brummer10** [jatinchowdhury18/RTNeural#130]
Hi
Thanks for this nice engine. It's very lightweight in DSP load.  
I've integrated RTNeural as submodule into guitarix now allowing to load json or aidax files into the modeler.
It works very well and was straight forward to integrate. Nice work from you!
https://github.com/brummer10/guitarix

regards
hermann

**Comment by brummer10** [comment]
I implemented RTNeural in a other project
https://github.com/brummer10/Ratatouille.lv2

This is a Neural Model loader/mixer for Linux/Windows allow to load NAM and RTNeural models and mix them.

**Comment by jatinchowdhury18** [comment]
Ah, sorry I'm only seeing this now! I'm a big fan of guitarix, so this means a lot to me :).

I've added guitarix to the [RTNeural README](https://github.com/jatinchowdhury18/RTNeural/blob/main/README.md#powered-by-rtneural), please let me know if you'd like me to edit the description in any way.

**Comment by brummer10** [comment]
Thanks. 
I'm glad you like guitarix. Now, with the RTNeural module it becomes even better.
